import { TacticalFormation, PitchSlot } from './types';

export const FORMATION_PRESETS: Record<TacticalFormation, Omit<PitchSlot, 'playerId' | 'isCaptain' | 'isPenaltyTaker' | 'isFreeKickTaker' | 'isCornerTaker'>[]> = {
  '4-3-3': [
    { id: 'pos-gk', roleName: 'GK', x: 50, y: 88 },
    { id: 'pos-lb', roleName: 'LB', x: 15, y: 70 },
    { id: 'pos-lcb', roleName: 'LCB', x: 38, y: 72 },
    { id: 'pos-rcb', roleName: 'RCB', x: 62, y: 72 },
    { id: 'pos-rb', roleName: 'RB', x: 85, y: 70 },
    { id: 'pos-cdm', roleName: 'CDM', x: 50, y: 52 },
    { id: 'pos-lcm', roleName: 'LCM', x: 30, y: 40 },
    { id: 'pos-rcm', roleName: 'RCM', x: 70, y: 40 },
    { id: 'pos-lw', roleName: 'LW', x: 18, y: 20 },
    { id: 'pos-st', roleName: 'ST', x: 50, y: 15 },
    { id: 'pos-rw', roleName: 'RW', x: 82, y: 20 },
  ],
  '4-2-3-1': [
    { id: 'pos-gk', roleName: 'GK', x: 50, y: 88 },
    { id: 'pos-lb', roleName: 'LB', x: 15, y: 70 },
    { id: 'pos-lcb', roleName: 'LCB', x: 38, y: 72 },
    { id: 'pos-rcb', roleName: 'RCB', x: 62, y: 72 },
    { id: 'pos-rb', roleName: 'RB', x: 85, y: 70 },
    { id: 'pos-ldm', roleName: 'LDM', x: 35, y: 55 },
    { id: 'pos-rdm', roleName: 'RDM', x: 65, y: 55 },
    { id: 'pos-lam', roleName: 'LAM', x: 20, y: 35 },
    { id: 'pos-cam', roleName: 'CAM', x: 50, y: 32 },
    { id: 'pos-ram', roleName: 'RAM', x: 80, y: 35 },
    { id: 'pos-st', roleName: 'ST', x: 50, y: 15 },
  ],
  '4-4-2': [
    { id: 'pos-gk', roleName: 'GK', x: 50, y: 88 },
    { id: 'pos-lb', roleName: 'LB', x: 15, y: 70 },
    { id: 'pos-lcb', roleName: 'LCB', x: 38, y: 72 },
    { id: 'pos-rcb', roleName: 'RCB', x: 62, y: 72 },
    { id: 'pos-rb', roleName: 'RB', x: 85, y: 70 },
    { id: 'pos-lm', roleName: 'LM', x: 15, y: 44 },
    { id: 'pos-lcm', roleName: 'LCM', x: 38, y: 46 },
    { id: 'pos-rcm', roleName: 'RCM', x: 62, y: 46 },
    { id: 'pos-rm', roleName: 'RM', x: 85, y: 44 },
    { id: 'pos-ls', roleName: 'LS', x: 36, y: 18 },
    { id: 'pos-rs', roleName: 'RS', x: 64, y: 18 },
  ],
  '3-5-2': [
    { id: 'pos-gk', roleName: 'GK', x: 50, y: 88 },
    { id: 'pos-lcb', roleName: 'LCB', x: 25, y: 74 },
    { id: 'pos-cb', roleName: 'CB', x: 50, y: 75 },
    { id: 'pos-rcb', roleName: 'RCB', x: 75, y: 74 },
    { id: 'pos-lwb', roleName: 'LWB', x: 12, y: 48 },
    { id: 'pos-lcm', roleName: 'LCM', x: 34, y: 48 },
    { id: 'pos-cam', roleName: 'CAM', x: 50, y: 36 },
    { id: 'pos-rcm', roleName: 'RCM', x: 66, y: 48 },
    { id: 'pos-rwb', roleName: 'RWB', x: 88, y: 48 },
    { id: 'pos-ls', roleName: 'LS', x: 36, y: 18 },
    { id: 'pos-rs', roleName: 'RS', x: 64, y: 18 },
  ],
  '3-4-3': [
    { id: 'pos-gk', roleName: 'GK', x: 50, y: 88 },
    { id: 'pos-lcb', roleName: 'LCB', x: 25, y: 74 },
    { id: 'pos-cb', roleName: 'CB', x: 50, y: 75 },
    { id: 'pos-rcb', roleName: 'RCB', x: 75, y: 74 },
    { id: 'pos-lm', roleName: 'LM', x: 15, y: 46 },
    { id: 'pos-lcm', roleName: 'LCM', x: 38, y: 48 },
    { id: 'pos-rcm', roleName: 'RCM', x: 62, y: 48 },
    { id: 'pos-rm', roleName: 'RM', x: 85, y: 46 },
    { id: 'pos-lw', roleName: 'LW', x: 20, y: 20 },
    { id: 'pos-st', roleName: 'ST', x: 50, y: 15 },
    { id: 'pos-rw', roleName: 'RW', x: 80, y: 20 },
  ],
  '5-3-2': [
    { id: 'pos-gk', roleName: 'GK', x: 50, y: 88 },
    { id: 'pos-lwb', roleName: 'LWB', x: 12, y: 64 },
    { id: 'pos-lcb', roleName: 'LCB', x: 30, y: 72 },
    { id: 'pos-cb', roleName: 'CB', x: 50, y: 74 },
    { id: 'pos-rcb', roleName: 'RCB', x: 70, y: 72 },
    { id: 'pos-rwb', roleName: 'RWB', x: 88, y: 64 },
    { id: 'pos-lcm', roleName: 'LCM', x: 30, y: 45 },
    { id: 'pos-cm', roleName: 'CM', x: 50, y: 42 },
    { id: 'pos-rcm', roleName: 'RCM', x: 70, y: 45 },
    { id: 'pos-ls', roleName: 'LS', x: 36, y: 18 },
    { id: 'pos-rs', roleName: 'RS', x: 64, y: 18 },
  ],
  '4-1-4-1': [
    { id: 'pos-gk', roleName: 'GK', x: 50, y: 88 },
    { id: 'pos-lb', roleName: 'LB', x: 15, y: 70 },
    { id: 'pos-lcb', roleName: 'LCB', x: 38, y: 72 },
    { id: 'pos-rcb', roleName: 'RCB', x: 62, y: 72 },
    { id: 'pos-rb', roleName: 'RB', x: 85, y: 70 },
    { id: 'pos-cdm', roleName: 'CDM', x: 50, y: 56 },
    { id: 'pos-lm', roleName: 'LM', x: 15, y: 38 },
    { id: 'pos-lcm', roleName: 'LCM', x: 38, y: 40 },
    { id: 'pos-rcm', roleName: 'RCM', x: 62, y: 40 },
    { id: 'pos-rm', roleName: 'RM', x: 85, y: 38 },
    { id: 'pos-st', roleName: 'ST', x: 50, y: 15 },
  ],
  '4-5-1': [
    { id: 'pos-gk', roleName: 'GK', x: 50, y: 88 },
    { id: 'pos-lb', roleName: 'LB', x: 15, y: 70 },
    { id: 'pos-lcb', roleName: 'LCB', x: 38, y: 72 },
    { id: 'pos-rcb', roleName: 'RCB', x: 62, y: 72 },
    { id: 'pos-rb', roleName: 'RB', x: 85, y: 70 },
    { id: 'pos-lm', roleName: 'LM', x: 15, y: 44 },
    { id: 'pos-lcm', roleName: 'LCM', x: 34, y: 46 },
    { id: 'pos-cm', roleName: 'CM', x: 50, y: 48 },
    { id: 'pos-rcm', roleName: 'RCM', x: 66, y: 46 },
    { id: 'pos-rm', roleName: 'RM', x: 85, y: 44 },
    { id: 'pos-st', roleName: 'ST', x: 50, y: 18 },
  ],
};

export function getDefaultPitchSlots(formation: TacticalFormation, existingSlots?: PitchSlot[]): PitchSlot[] {
  const preset = FORMATION_PRESETS[formation] || FORMATION_PRESETS['4-3-3'];
  return preset.map((slot, index) => {
    const existing = existingSlots?.[index];
    return {
      id: slot.id,
      roleName: slot.roleName,
      x: slot.x,
      y: slot.y,
      playerId: existing?.playerId,
      isCaptain: existing?.isCaptain || false,
      isPenaltyTaker: existing?.isPenaltyTaker || false,
      isFreeKickTaker: existing?.isFreeKickTaker || false,
      isCornerTaker: existing?.isCornerTaker || false,
    };
  });
}
